### ISSUE TITLE
Crash - When shift clicking item into Request Table

### ISSUE THREAD

**Issue by SonarSonic** [MrRiegel/Storage-Network#10]
http://pastebin.com/bmdWxwdB

Crashed when shift clicking some seeds into the Request Table, I had 4 storage cables on the network with 4 chests.

**Comment by SonarSonic** [comment]
UPDATE: since shift clicking those seeds now when I open any block in the network I get the same crash. Also had the same issue with the Remote Accessor

**Comment by KidsDontPlay** [comment]
That's weird. I didn't have this crash ever and it seems your are the first one

**Comment by SonarSonic** [comment]
You must be using a different Forge Version, that's my guess anyway.

**Comment by KidsDontPlay** [comment]
I have the same version

**Comment by SonarSonic** [comment]
Just to confirm the fix worked :)
