### ISSUE TITLE
Priority system

### ISSUE THREAD

**Issue by topher2010** [MrRiegel/Storage-Network#103]
It appears prioritization doesn't work with Storage Network.  One bus would be set to 20, one would be set to -20, and the one set to 20 doesn't get enough of the item it's supposed to.

**Comment by KidsDontPlay** [comment]
That's not the way priority works.
If you insert an item into the network it will prefer the storage device with higher priority. it has nothing to do with amount of items

**Comment by topher2010** [comment]
i realize that. the bus set to priority 20 doesnt get priority over the bus with priority -20. thats what im saying.

**Comment by KidsDontPlay** [comment]
what type of bus do you use?

**Comment by topher2010** [comment]
network export device

**Comment by KidsDontPlay** [comment]
it doesn't mean that the export devices with lower priority won't get any items until the devices with higher priority are full.
but if you have 2 export devices with e.g. coal and you have 1 coal in your system the coal will be inserted into the higher priority chest (or whatever)
