### ISSUE TITLE
Crash with unknown cause

### ISSUE THREAD

**Issue by primetoxinz** [MrRiegel/Storage-Network#106]
[crash-2016-11-20_20.08.30-client.txt](https://github.com/MrRiegel/Storage-Network/files/602546/crash-2016-11-20_20.08.30-client.txt)
From what I can tell either theWorld or objectMouseOver is null... which neither makes sense. very odd

**Comment by canitzp** [comment]
not the objectMouseOver is null, but he tries to get the tile entity from a null position and I don't knoe if this works. in some rare cases the world can be null like you said, so let's investigate this
