### ISSUE TITLE
[enhancement] various ideas!

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#116]
Power enhancements

#1 Voltage upgrades on power cable, I can tell the current version has RF transfer setup at 1000 rf/t, but it could be more interesting to have something upgradable like the storage system in the form of voltage upgrades, start with 128rf/t for standard power transfer, and then multiply by 4 for each voltage upgrade applied so:
no upgrades = 128 rf/t
1 upgrade = 512rf/t
2 upgrades = 2048rf/t
3 upgrades = 8192 rt/t
4 upgrades = 32768 rf/t

#2 power priority, add priority filter (same as other connectors) to power connector, so we can tell the system where to route power first.

#3 Added to the previous point, make the network core to have higher priority over any other block while transferring power (so always fully power the network core first over everything) since if you run out of power in the network core, nothing works!!!

Toggle cable enhancements

#1 when hitting it with the wrench make is to that the default state is off, and you need redstone to power it on. So invert the current work setup.

#2 change the model of the cable to a dynamic model, that when we attach a button or lever a small platform shows up where the object gets attached instead of floating mid air, looks weird.

Item Mirror

#1 make it like half the size, or even a quarter of the current block size (since you made them similar to a drawer, look for half drawer, same thing). Now this is just personal preference probably, so having one big version and one small version might be better so everyone is happy. My logic behind this idea is that the mirror block is more like an extraction insertion block, so it really doesn't need to be so big.

that is all for now... =D

thanks.

**Comment by KidsDontPlay** [comment]
power:
1. the transfer rate is 1000 + (number of energy cells*1000). So you can upgrade the rate with energy cells.
2. good idea
3. already added. the network will only transfer energy if the core has more than 75%

toggle:
1. ok
2. should be possible

mirror:
I thought about this but it looks weird when the cable connects from the side

**Comment by winsrp** [comment]
power

1. OHH... didn't knew that, I was wondering why you had a power storage cube, maybe you want to document that, is a good thing to know that is not written anywhere. Also adding to this, can you put a config option to set the increment of each added energy cell, default config would be just 1000, I personally would set it to 128 or 256, since the energy cell recipe is quite cheap.

2. =D

3. kind of noticed, but still bugs me that is not full =D

toggle

1. =D

2. =D (not that important, just nice to have)

item mirror

1. hmm... true true, I would say make it flat like a screen panel and show the items there, and don't allow connections on the sides only the back, but that would be a pain in the ass for u to make.... would look cool, but I don't want to bother you too much, you are too nice.

Thanks. 

Looking forward for an updated version on the curse site!!.
