### ISSUE TITLE
crashed while trying to see how much storage network changed

### ISSUE THREAD

**Issue by SDUBZ** [MrRiegel/Storage-Network#120]
forge:1.10.2-2185

storage network version:1.10.2-2.0.8

crash report:
[crash-2016-12-09_04.11.43-server.txt](https://github.com/MrRiegel/Storage-Network/files/640115/crash-2016-12-09_04.11.43-server.txt)

what happend: i was exporting out of a chest dropped a stack of chest and crash

**Comment by KidsDontPlay** [comment]
can you show me a screenshot of your setup?

**Comment by SDUBZ** [comment]
umm i couldnt get back in my world doesnt matter i worked out what i was doing wrong so you can close this now if you want :D

**Comment by KidsDontPlay** [comment]
I guess you attached a storage device to an interface that belongs to the same network. You can enable STOPTICK in the conig file, enter your world an remove crash causing blocks.
