### ISSUE TITLE
[Power stuff][2.0.8] enhancements, compatibility and issues

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#122]
First enhancements (which could potentially fix some issues not sure).

1. I just noticed that the network core gets updated with another bar when there are energy cells, and the more cells are in the system the "longer" it gets by % seen. Why not make it just part of the normal bar, and total system power? I know that the power cells are stored energy to transfer but, get to the issues part first and see if it helps, if you are keeping the second bar, maybe you can put it on the right side of the screen, it might look better as computer screens are wider than they are taller, just saying.

2. Add the RF/t transfer total to the network core information displayed (base rf/t + (rf/t per energy cell * amount of energy cells)) (people playing on the server not always know what is in the config files =D), I saw you added the energy transfer rate by cell, is that what I think it is (YAY!!!), eh ... I mean.. thanks. =D

Compatibility

1. While hooking the network energy interface to Immersive engineering generators it does not extracts or moves energy, but if I put one of their connectors (IE connectors) hooked to the network core it does works, I tried the Kinetic dynamo with the windmill and water wheel, also the thermoelectric generator and both fail, the diesel generator does works so not sure if the problem is in your mod or theirs.

Issues

Now this is a really strange one, so let me see if I manage to explain it correctly. Say I hook one network core and one energy cell, and on the other side a generator (any kind, I have tried Immersive engineering diesel generator, RFTool coal generator, Advanced generators mods, even creative power sources from all those mods) on the described setup everything works fine. Now if you put 9 empty power cells to the network the following happens:

Network core gets depleted by around 1/10 of the power, and at the same time the powercells start to get filled, the drink some power for about 2 secs, then stop for around 3 secs, then continue drawing for 2 secs, then stop again for another 2 or 3 secs, and so on... the behavior gets worst the more powercells are in the system, I'm still using the standard file config setup in case you need to know.

That is all for this one, lol. sorry to be such a annoyance.

**Comment by KidsDontPlay** [comment]
I fixed the 'issue' and added RF/t to the GUI.
But I don't know why the energy interface isn't compatible with IE generators. I have similar problems with enderIO energy conduits. They won't connect to IE generators as well.

**Comment by winsrp** [comment]
cool I'll give it a try later today, tx

**Comment by winsrp** [comment]
look to be working great. took a while to find the RF/t value, lol... but found it tx. (I was actually asking for it to be put where you have the network size:x -> network cable: x -> etc etc.. but is fine as long as is there.
