### ISSUE TITLE
A few requests 

### ISSUE THREAD

**Issue by Carbon-Ghost** [MrRiegel/Storage-Network#15]
Hello, I wanted to say thanks a lot you made this mod >.<

I had a few requests though, may we have an autocrafting cable thing and an autocrafting table for crafting that we can use with the system ?

May we have / I backport this gem to 1.7.10 ? ( actually, if you want, may we have a talk to merge dev teams ? Speiger and me had the logistic storage project but we couldn't finish due to lack of devs... )

IC2 classic eu support :3

:D

**Comment by KidsDontPlay** [comment]
hi,
I'm working on an autocrafting system.
I have no intention to backport the mod to 1.7.10. There are enough mods like this (AE2, LP, ProjectRed)

**Comment by Carbon-Ghost** [comment]
:D 
None are exactly what I would have wanted though :C I want an AE like mod with easy autocrafting and logistics D:
So erm, may we have permission to port it under another form ? Pwease :3 All credits will ofc go to you :D I also will ask Speiger for IC2 classic support :3
This mod is what I missed for nearly a year....
Now this, IC2, BC, Project E and my own GregTech approved version.... :3

**Comment by KidsDontPlay** [comment]
ok, go for it
you have my permission

**Comment by Carbon-Ghost** [comment]
yay :D
