### ISSUE TITLE
[1.8.0] Speed upgrade in fluid import cable doesn't work properly

### ISSUE THREAD

**Issue by MrGraphic** [MrRiegel/Storage-Network#20]
There you go ;). As in title, it works at the begining then stops pretty fast and fluids starts to move at standard - very slow, speed. 
By the way fluid transfer is a little bit too slow in my opinion especially that network can drain from one tank at once.

**Comment by KidsDontPlay** [comment]
mmh.. I can't reproduce. What cables do u use? and what tanks?

**Comment by MrGraphic** [comment]
Simple setup with many Buildcraft tanks like in this image http://i.imgur.com/o0Q6CRG.jpg
Import cable also hooked to bc Tank. It starts to suck liquid as expected on 4x speed upgrade and after few buckets slows down to speed level without upgrades. I will try build from Curse but I dubt that this will change much. Will try also setup with diffrent tanks.

**Comment by MrGraphic** [comment]
Ok I found the issue. At default settings CableMaster can't handle energy demand of fully upgraded import cable. One side of CM can accept only 120RF/t while IC at full speed uses like 600RF/t per transfer - that's a lot hehe.
