### ISSUE TITLE
Partial Team adhesion request

### ISSUE THREAD

**Issue by Carbon-Ghost** [MrRiegel/Storage-Network#21]
Hi, I wanted to request a partial team adhesion with you guys, as a texturer, to be fair, all textures are already done on my side, they are nicer AE like style and AE2 team approved textures, just wanted to contribute to the mod development a bit. 

Story is, we planned doing a mod called logistical storage, but then one of the members was away due to the refugial crisis thing ( he helped refugees ) so mod dev was put on standby. 
All textures are done though. 

And me trying to backport it... failed horribly, 1.8.9 to 1.7.10 is to hard for me D:

**Comment by KidsDontPlay** [comment]
what exactly do you mean by adhesion? do you support this mod with your textures?

**Comment by Carbon-Ghost** [comment]
Sorta yup ;D They are already all done, and I can "merge" them with current :D

**Comment by KidsDontPlay** [comment]
Ok, could you show the textures?

**Comment by Carbon-Ghost** [comment]
![assets_blocks_logistics](https://cloud.githubusercontent.com/assets/10200094/13815765/24d9c4f6-eb8c-11e5-89ac-6f6ce29b7a1e.png)
![assets_items](https://cloud.githubusercontent.com/assets/10200094/13815771/2a7dec3e-eb8c-11e5-97f3-627652623807.png)

**Comment by Carbon-Ghost** [comment]
it was for the unfinished logistic storage mod, so yeah
The items was silicon, circuit 1, circuit 2, requester. 
Blocks are : 
- Logistical Core
- Requesting Terminal
- Logistical External Reader
- Logistical Crafting Memory Chassis
- Logistical Auto-Crafter
- Logistical System I/O gate block ( input )
- Logistical System I/O gate block ( output )
- Logistical Storage Reader
- Logistical Cables
  Lore of these blocks so you know which texture to use compared to the old functions one : 
  Original lore : 

Descriptions :

-Logistical core : At least one is required for a system, allows you to store 100 000 ender-vibrating pulses ( 1 EVP == 1 EU == 4 RF, conventional Forge conversions ), but it also have some neat features ( shows current crafting jobs, crafting knowledge, energy consumption, time left before the end of a crafting job, allows you to bind a wireless requesting terminal to access your system from anywhere in your world, as long you have chunk loading and energy in the logistic system, no need to power this item though ). 
-Requesting terminal : Allow the access of items through the logistic system ( you can access to all storage containers that are connected through a Logistic Storage Reader ). 
-Logistical Crafting Memory Chassis : Allow you to print new recipes in it’s internal disk for the system auto-crafting knowledge and store these disk-printed recipes, can hold up 9 crafting recipes, selecting one of the squares in the GUI allow you to set a new one or modify/delete an existing one, NEI compatible.
-Logistical Auto-Crafter : Allow you to craft items that are requested through a Requesting terminal, the requested items can only be the ones that are stored in the system memory ( in Logistical Crafting Chassis or Logistical External Auto-Crafter ), will execute a crafting process at the rate of 1 operation every half a second, you can accelerate it by halving the time between operations using a speed upgrade.
-Logistical External Reader : Allow you to send items in external machines, similarly to the Logistical Auto-Crafter, it will execute the action if requested by the Requesting terminal. It has an internal Memory Chassis, meaning you will be able to set the machine material requirement for the recipes directly in the Logistical External Reader ( can hold up 27 machine material requirement for the recipes, selecting one of the squares in the GUI allow you to set a new one or modify/delete an existing one, once you open one up, you will be able to set up to 9 inputs and specify up to 9 outputs that are requested ), will attempt to push the materials if it’s possible at the rate of 1 operation every half a second, you can accelerate it by halving the time between operations using a speed upgrade.
-Logistical System I/O gate block ( input/output ) : Allow you to export and import items in and out of your system, GUI allows to set extraction speed ( 1 to 64 items in **_._ seconds ) and set it to import or export mode and filter items, it will also change the block face arrows in blue or orange and invert their direction so color blind people can see in what mode it is, it’s used to pipe in or out items from/for hoppers, BC & TE pipes, pulse I/O gate block, AE2 buses ( see below how to make a ME system connect to a Logistical storage one ), etc..
-Logistical Storage Reader : Allow you to access containers of item from your Requesting Terminal.
-Logistical Cables : Allow you to connect all the components of a Logistical system. 
-Pulse I/O gate block and Pulse cables : Those cables and I/O gate don’t require energy, those are supposed to be an upgrade to vanilla hoppers / BC cables as they are faster, don’t leak, are easier to setup. A Pulse system is similar to a Logistical one, in a way the cable don’t really do much, for extracting items from containers and for piping them out of the system, you will need to use Pulse I/O gates. I/O gates are similar to their advanced Logistical counterparts, like them, there is no delay travel between 2 gates ( unlike them, there is no complex system to work with, only gates ), you can also set it to import or export mode and filter items in it’s GUI though unlike it’s superior counterpart, speed is constant at a rate of 4 items per second being pulled or pushed for a gate. Their main advantage is the fact they are energy-less, so they are better for small scale automation where a logistical system won’t be worth the hassle to sustain energy wise. You can connect the gates on 16 different frequencies ( 0-15 ), so you can have 2 sets of different frequencies pulse gates on the same system that work independently ( you can connect them if you put one gate on output mode with a frequency of x and a one gate on input output mode with a frequency of y with y =! x ). 
Special blocks : 
-Logistical Electrical Energy Feeder : A block that is used to provide power to your system, will accept IC2 EU, Immersive engineering and Magneticraft electricity, Resonant Engine electricity, Electricraft energy and Mekanism universal power by default, configurable. Rate to create 1 EVP is 1 EU == 1 EVP ( Based on EU, the conversion will depend on the mod by using the value it uses to convert it’s own energy to EU, exemple 10 mekanism joules == 1 EU == 1 EVP ). 
-Logistical Redstone Flux Magnetostatic Feeder : A block that is used to provide power to your system, will accept RF. Rate to create 1 EVP is 4 RF == 1 EVP. 
Note that if there is no Electric provider mods, the Logistical Electrical Energy Feeder won’t be loaded, same thing for the RF one, if no mods that adds power is detected, you will still be able to provide power by applying a redstone signal to a core which will generate 1 EVP per second ( by default off ). 
-Ore Smelter : Early game ore doubling, will perform 1 action at the cost of 8x the normal furnace fuel cost for doubling any ores that is registered in the OD ( except uranium if IC2 is present, a config file will exist for modpack makers to blacklist ores that might need a specific processing machine ). Might not be wise to use for some ores like redstone due to the fact they have a better output of material when mined. It takes 15 seconds to perform 1 action. 
-Quartz Chest : A quartz carved chest that has a capacity of a double chest. Useful for vanilla. 

Optional TO-DO blocks :
-Assembling Pulse crafter : Stores 1 recipe, simply crafts the recipe when the materials are present. 
-Logistical-ME Bridge : Allow you to access all your items and crafting requests that are in your ME system and vice-versa.

How work the energy consumption :
By default one core provides a buffer of 100 000 EVP :
By default, the consumption of energy is the following : 
- A crafting operation consumes 10 EVP. 
- An external reader operation consumes 50 EVP. 
- A terminal manipulation ( putting in stacks and taking out stacks are free ) consumes 5 EVP per crafting requests. 
- A gate operation consumes 5 EVP. 
- A storage reader consumption will be free when it will try to put items and out of a container. 
- A chassis and an external reader will consume 5 EVP every time you print in a new recipe in it’s memory. 
  In hardmode ( Default on for balance reasons ), most blocks consume 2x more energy and some blocks have a passive usage of energy every 5 seconds ( the energy it consumes is what it should consume in 1 second times 5, to avoid lags ) : 
- A crafting operation consumes 20 EVP. 
- An external reader operation consumes 100 EVP. 
- A terminal manipulation ( putting in stacks and taking out stacks will cost 5 EVP ) consumes 10 EVP per crafting requests and will consume 25 EVP every 5 seconds passively. 
- A gate operation consumes 10 EVP. 
- A storage reader will consume 10 EVP when it will try to put items and out of a container and will consume 25 EVP every 5 seconds passively.  
- A chassis and an external reader will consume 10 EVP every time you print in a new recipe in it’s memory. 

Note that the system will prioritize the energy consumption in this order : 
1 : - The action of taking things out and putting them back in the system ( if Hardmode is activated )
2 : - The autocrafting processes if it can craft the item
3 : - The gate communication with the external piping

**Comment by Carbon-Ghost** [comment]
btw textures are : Bottom, Top, and sides

**Comment by KidsDontPlay** [comment]
oh, thats a wall of text.
why did you write the features of your mod? do you want me to adapt the ideas?
your mod seems very more elaborate than mine.

**Comment by Carbon-Ghost** [comment]
1 : Hehe, I told you, it was from an older never finished project, it's just for you to inspire yourself if you want to + know what textures was equivalent to your current machines using images and description ;)
2 : Well, you don't have to, I don't want anything from you :3 Just me helping, but feel free reusing ideas :D 
3 : Thanks, but it was never finished D:

**Comment by KidsDontPlay** [comment]
nice ideas.
I failed to implement an autocrafting system. It was too complicated.
I play with the idea to rewrite my mod. It isn't coded well and maybe not that user-friendly.
The recipes are too simple. Automation of your complete 'economy' should be worth more than the status quo. The names of your blocks sound much more professional and technical. (Mine are simple cause I'm not a native speaker.)
At least I'm not happy with my models, textures and GUI.
But I don't want make just a copy of AE. Therefore I didn't create something like the ME-Interface.
Are you able to programm?

**Comment by Carbon-Ghost** [comment]
1 : Aow, what have you tried todo ?
2 : Do it as you feel ;) 
3 : " Automation of your complete 'economy' " What do you mean here ^^ ?
4 : You mean my mod is worth more than a status quo ? if so thanks ;)
5 : Thanks again :D 
6 : You don't like your textures ? I think they are good too ;)
7 : Well while the idea of my crafter thing may be similar, it is original, AE2 dev approved ( the whole mod idea ;)  )
8 : I am too bad atm imo. sorry D:

**Comment by KidsDontPlay** [comment]
1. the crafting should be similiar to AE crafting. I was able to get craftable amount of an item. But I don't know how to calculate the missing items. And the real crafting is more complicated.
2. I mean automate your processing of items (like [this](http://i.imgur.com/r8Z5bFL.jpg))
3. No, I mean it's to easy to setup a network with my mod. Stone, iron, hopper, lapis is very cheap.
4. Ok, the textures are fine, but the GUI should be reworked.

**Comment by Carbon-Ghost** [comment]
1 : yup, as for that, I have a mathematical potential solution, though working it out in algorithmic might be hard..
2 : Memories.. though that was the point of the "pulse" stuff that acted more like pipes than a network. 
3 : My mod idea is averagely expensive but has the inconvenience of being bulky and slower than AE, however no channel or cpu limitation is it's main advantage ( kinda like old AE ). 
4 : I like your GUI :P

**Comment by Carbon-Ghost** [comment]
Are you going to use textures in the end :3 ?

**Comment by KidsDontPlay** [comment]
i dont think so

**Comment by Carbon-Ghost** [comment]
kk ^^
