### ISSUE TITLE
Cable master only pulls 400 RF max, but sometimes it needs more juice =D

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#26]
just as the title says, sometimes 400RF/t is not enough to keep the cable master running smooth. You might want to increase the max based on consumption needs.

**Comment by KidsDontPlay** [comment]
400 is pretty much. maybe you should lower the energy multiplier in the config.
you would need a lot of AE machines to reach 400 rf/t.

**Comment by winsrp** [comment]
well I do have a lot of machines, chest, and now with liquids, plus the neotech builder extracting elements like crazy, a automatic tree planter chopper, so its 4 floors full of cables pipes and stuff, and I haven't even done half of it, and it's already sucking 400... it's fun that needs more power, so you need to work your way into making more power, but if the network stops working due to not being able to pull as much power as needed then everything stops working.

**Comment by KidsDontPlay** [comment]
ok, I'll add an option to alter the maxReceive.
should I remove the feature that the consumption is in proportion to the amount of cables?

**Comment by winsrp** [comment]
the consumption in proportion to cables works wonders for game balance, you don't want people having a billion cables with only 5rf/t... you want more automation, then you need more power... you should actually just let the system suck as much as it needs no max needed.

**Comment by KidsDontPlay** [comment]
ok, it's committed. Is 2³¹-1 RF/t enough?

**Comment by winsrp** [comment]
yeah.. should be, lol
