### ISSUE TITLE
missing images, and what is the indicator for

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#27]
new fluid accessors don't have image (this might not be a bug, but just wanted to point it out just in case) and what is the indicator block for, can't figure it out.

**Comment by KidsDontPlay** [comment]
I know the textures are missing.
put an item into the indicator. it has to be connected to the network. the tooltip on the button will answer your question

**Comment by winsrp** [comment]
oh, would you look at that... very handy, but you always seems to think too small... how about adding more field to that indicator, just like the filters in the connection pipes, if any of those items are missing send a signal.

For example, I have an automatic generator for axes, it does cobble, andesite, diorite and granite axes (yes from another mod), but it kind of those them randomly as items come into the network, those are feed into the tree chopper, so when there are no axes in the network (and I can put all 4 in the list), turn on the generator sequence on (which does 4 axes at a time).

but it can be part of an upgrade, for more fields in the GUI, don't give all the goody goodies all at once, scalability is nice in minecraft enviroments, so you can start small and upgrade to bigger better things. (could be applied to the other cables too in the future, lets say... filter upgrade, and maybe add up to 2 lines of filters in the cables =D), also better upgrades, more power needed!

Thank for listening Santa... =D

**Comment by winsrp** [comment]
I know I'm a nuisance but your mod is great! And I would just like for it to be even better.
