### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#28]
I don't know why I tried to put upgrades on a blue cable... but when I did... it crashed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 3/17/16 1:51 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at mrriegel.storagenetwork.gui.cable.GuiCable.func_73864_a(GuiCable.java:186)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at mrriegel.storagenetwork.gui.cable.GuiCable.func_73864_a(GuiCable.java:186)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: mrriegel.storagenetwork.gui.cable.GuiCable

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['winsrp'/201, l='MpServer', x=27.79, y=64.00, z=75.62]]
    Chunk stats: MultiplayerChunkCache: 1089, 1089
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: 48.00,64.00,168.00 - World: (48,64,168), Chunk: (at 0,4,8 in 3,10; contains blocks 48,0,160 to 63,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 790584 game time, 6191 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: true. Cheats: false
    Forced entities: 78 total; [EntityItem['item.item.owlEgg'/1846298, l='MpServer', x=49.38, y=76.00, z=17.13], EntityOwl['Owl'/968711, l='MpServer', x=-8.50, y=77.00, z=33.44], EntitySheep['Sheep'/33, l='MpServer', x=-51.53, y=62.63, z=1.38], EntityOwl['Owl'/34, l='MpServer', x=-10.44, y=77.00, z=24.53], EntitySheep['Sheep'/37, l='MpServer', x=-32.72, y=66.00, z=-1.53], EntitySheep['Sheep'/38, l='MpServer', x=-43.94, y=67.00, z=-2.31], EntityItem['item.item.owlEgg'/1837878, l='MpServer', x=88.13, y=82.00, z=23.13], EntityItem['item.item.owlEgg'/1825589, l='MpServer', x=2.13, y=71.00, z=16.22], EntityCreeper['Creeper'/1835053, l='MpServer', x=81.50, y=17.00, z=76.50], EntityItem['item.item.owlEgg'/1834280, l='MpServer', x=45.53, y=81.00, z=24.19], EntityPlayerSP['winsrp'/201, l='MpServer', x=27.79, y=64.00, z=75.62], EntityOwl['Owl'/56, l='MpServer', x=-12.56, y=73.94, z=29.16], EntityOwl['Owl'/66, l='MpServer', x=45.44, y=81.00, z=20.56], EntityBat['Bat'/1854303, l='MpServer', x=-43.25, y=37.03, z=111.25], EntityOwl['Owl'/68, l='MpServer', x=-4.38, y=75.00, z=29.50], EntityItem['item.item.owlEgg'/1836888, l='MpServer', x=45.31, y=77.00, z=41.56], EntityItem['item.item.owlEgg'/1813853, l='MpServer', x=49.13, y=82.00, z=29.66], EntityOwl['Owl'/71, l='MpServer', x=16.13, y=79.00, z=25.66], EntityOwl['Owl'/82, l='MpServer', x=51.76, y=82.00, z=21.00], EntityOwl['Owl'/83, l='MpServer', x=90.47, y=77.00, z=37.47], EntityRabbit['Rabbit'/84, l='MpServer', x=-7.56, y=62.63, z=34.69], EntityItem['item.item.dyePowder.black'/1818703, l='MpServer', x=40.72, y=5.00, z=90.78], EntityItem['item.item.owlEgg'/1812556, l='MpServer', x=10.59, y=66.00, z=30.41], EntityOwl['Owl'/92, l='MpServer', x=-3.25, y=76.00, z=21.81], EntityOwl['Owl'/94, l='MpServer', x=13.41, y=73.00, z=14.47], EntityOwl['Owl'/99, l='MpServer', x=77.19, y=78.94, z=28.19], EntitySquid['Squid'/1848954, l='MpServer', x=76.38, y=52.09, z=103.41], EntityOwl['Owl'/105, l='MpServer', x=39.03, y=77.06, z=21.22], EntityOwl['Owl'/106, l='MpServer', x=22.53, y=77.00, z=23.53], EntityOwl['Owl'/109, l='MpServer', x=31.63, y=83.00, z=29.75], EntityOwl['Owl'/110, l='MpServer', x=35.44, y=85.00, z=30.53], EntityOwl['Owl'/114, l='MpServer', x=53.47, y=81.00, z=21.47], EntityOwl['Owl'/115, l='MpServer', x=78.34, y=80.00, z=20.03], EntityOwl['Owl'/117, l='MpServer', x=57.31, y=73.94, z=43.47], EntityOwl['Owl'/118, l='MpServer', x=75.53, y=81.00, z=27.53], EntityOwl['Owl'/120, l='MpServer', x=55.41, y=75.00, z=24.50], EntityOwl['Owl'/121, l='MpServer', x=59.44, y=78.00, z=32.47], EntityOwl['Owl'/123, l='MpServer', x=18.47, y=77.00, z=23.59], EntityOwl['Owl'/126, l='MpServer', x=58.50, y=78.00, z=32.53], EntityOwl['Owl'/127, l='MpServer', x=88.50, y=83.00, z=22.47], EntityOwl['Owl'/128, l='MpServer', x=74.47, y=81.00, z=29.44], EntityOwl['Owl'/129, l='MpServer', x=89.53, y=75.00, z=37.47], EntityOwl['Owl'/133, l='MpServer', x=45.44, y=82.00, z=32.50], EntityOwl['Owl'/137, l='MpServer', x=49.41, y=81.00, z=23.44], EntityOwl['Owl'/138, l='MpServer', x=22.50, y=78.00, z=32.44], EntityOwl['Owl'/141, l='MpServer', x=66.44, y=79.00, z=33.44], EntitySquid['Squid'/1848722, l='MpServer', x=71.03, y=53.63, z=78.72], EntityOwl['Owl'/142, l='MpServer', x=86.47, y=85.00, z=18.44], EntityOwl['Owl'/143, l='MpServer', x=81.44, y=85.00, z=32.44], EntityOwl['Owl'/144, l='MpServer', x=51.73, y=80.00, z=29.73], EntityBat['Bat'/1855884, l='MpServer', x=10.36, y=11.19, z=73.11], EntitySquid['Squid'/1826699, l='MpServer', x=-34.06, y=59.75, z=138.94], EntityOwl['Owl'/145, l='MpServer', x=63.50, y=79.00, z=20.50], EntityOwl['Owl'/146, l='MpServer', x=74.94, y=87.00, z=30.19], EntityOwl['Owl'/148, l='MpServer', x=69.47, y=81.03, z=34.09], EntityOwl['Owl'/149, l='MpServer', x=81.19, y=84.00, z=19.66], EntityBat['Bat'/1858441, l='MpServer', x=96.02, y=11.04, z=25.15], EntityOwl['Owl'/151, l='MpServer', x=51.53, y=83.00, z=25.13], EntityBat['Bat'/1859204, l='MpServer', x=-42.51, y=35.90, z=100.65], EntityOwl['Owl'/159, l='MpServer', x=77.53, y=79.00, z=30.53], EntityOwl['Owl'/164, l='MpServer', x=82.75, y=82.00, z=22.78], EntityOwl['Owl'/166, l='MpServer', x=50.56, y=82.00, z=22.59], EntityBat['Bat'/1858746, l='MpServer', x=10.22, y=23.55, z=3.52], EntityBat['Bat'/1858747, l='MpServer', x=27.30, y=17.56, z=0.23], EntityOwl['Owl'/168, l='MpServer', x=44.50, y=83.00, z=39.44], EntityItem['item.item.owlEgg'/1834163, l='MpServer', x=53.53, y=83.00, z=23.38], EntityOwl['Owl'/169, l='MpServer', x=75.59, y=87.00, z=30.56], EntityItem['item.item.owlEgg'/1861036, l='MpServer', x=18.97, y=77.00, z=23.28], EntityItem['item.item.owlEgg'/1843626, l='MpServer', x=-12.00, y=77.00, z=24.03], EntityItem['item.item.owlEgg'/1859238, l='MpServer', x=-5.81, y=77.00, z=29.56], EntityItem['item.item.owlEgg'/1824731, l='MpServer', x=46.88, y=81.00, z=22.41], EntityBat['Bat'/1846219, l='MpServer', x=24.66, y=14.96, z=6.20], EntityBat['Bat'/1860292, l='MpServer', x=-30.51, y=34.31, z=98.42], EntityOwl['Owl'/27352, l='MpServer', x=49.44, y=76.00, z=17.47], EntityBat['Bat'/1860295, l='MpServer', x=47.25, y=15.10, z=41.75], EntityItem['item.item.owlEgg'/1815536, l='MpServer', x=17.16, y=77.00, z=28.69], EntityBat['Bat'/1852403, l='MpServer', x=97.19, y=18.31, z=131.70], EntitySquid['Squid'/1848806, l='MpServer', x=58.25, y=51.44, z=104.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 540095328 bytes (515 MB) / 3013627904 bytes (2874 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 66
    FML: MCP 9.19 Powered by Forge 11.15.1.1762 Optifine OptiFine_1.8.9_HD_U_H4_pre 50 mods loaded, 50 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAA   Forge{11.15.1.1762} [Minecraft Forge](forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAA   darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE](minecraft.jar) 
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore](AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAA   MovingWorld{MC1.8.9-INDEV-H} [Moving World](movingworld-MC1.8.9-INDEV-H-full.jar) 
    UCHIJAAAA   ArchimedesShipsPlus{MC1.8.9-INDEV-G} [Archimedes' Ships Plus](archimedesshipsplus-MC1.8.9-INDEV-G.jar) 
    UCHIJAAAA   ArchitectureCraft{1.3.1} [ArchitectureCraft](ArchitectureCraft-1.3.1-mc1.8.9.jar) 
    UCHIJAAAA   bdlib{1.10.0.30} [BD Lib](bdlib-1.10.0.30-mc1.8.9.jar) 
    UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements](BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAA   BetterFoliage{2.0.3} [Better Foliage](BetterFoliage-MC1.8.x-2.0.3.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1926-universal.jar) 
    UCHIJAAAA   bookshelfapi{2.3.6} [Bookshelf](Bookshelf-API-1.8.9-2.3.6.jar) 
    UCHIJAAAA   caterpillar{0.0.0} [Caterpillar](Caterpillar-1.2.189b76.jar) 
    UCHIJAAAA   cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition](cfmce-1.0-mc1.8.9.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   EnderZoo{1.8.9-1.1.3.35} [Ender Zoo](EnderZoo-1.8.9-1.1.3.35.jar) 
    UCHIJAAAA   mcmultipart{1.0.8} [MCMultiPart](MCMultiPart-1.0.8-universal.jar) 
    UCHIJAAAA   reborncore{1.4.3.20} [RebornCore](RebornCore-1.8.9-1.4.3.20-universal.jar) 
    UCHIJAAAA   fluxedredstone{1.3.0.31} [FluxedRedstone](Fluxed Redstone-1.3.0.31.jar) 
    UCHIJAAAA   substratum{1.1.0.1} [Substratum](Substratum-1.8.9-1.1.0.1.jar) 
    UCHIJAAAA   foundry{1.4.0.0} [Foundry](Foundry-1.8.9-1.4.0.0.jar) 
    UCHIJAAAA   furnus{1.72} [Furnus](Furnus-1.8.9-1.72.jar) 
    UCHIJAAAA   pressure{1.3.0.23} [Pressure Pipes](pressure-1.3.0.23-mc1.8.9.jar) 
    UCHIJAAAA   advgenerators{0.9.19.8} [Advanced Generators](generators-0.9.19.8-mc1.8.9.jar) 
    UCHIJAAAA   inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks](InventoryTweaks-1.60-40.jar) 
    UCHIJAAAA   ironbackpacks{1.8-1.0.7} [Iron Backpacks](IronBackpacks-1.8-1.0.7.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.5.172} [Just Enough Items](jei_1.8.9-2.28.5.172.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   RadixCore{1.8.9-2.1.0} [RadixCore](RadixCore-1.8.9-2.1.0-universal.jar) 
    UCHIJAAAA   MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive](MCA-1.8.9-5.1.1.2-universal.jar) 
    UCHIJAAAA   MissingRecipies{0.1.0} [MissingRecipies](Missing Recipes 0.1.jar) 
    UCHIJAAAA   MoreFurnaces{1.5.0} [More Furnaces](MoreFurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.6.1%281.8.9%29.jar) 
    UCHIJAAAA   neotech{2.4.1} [NeoTech](NeoTech-1.8.9-2.4.1.jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter](OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   practicalities{2.0.0-b6} [Practicalities](practicalities-1.8.9-2.0.0-b6.jar) 
    UCHIJAAAA   progressiveautomation{1.6.35} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste](redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   rftools{4.23beta32} [RFTools](rftools-1.8.9-4.23beta32.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons](RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   wuppy29_simplerecipes{1.9.0} [Simple Recipes](Simple Recipes 1.8.0-1.9.0.jar) 
    UCHIJAAAA   SpiceOfLife{1.3.1} [The Spice of Life](SpiceOfLife-mc1.8.9-1.3.1.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.4} [Storage Drawers](StorageDrawers-1.8.9-2.4.4.jar) 
    UCHIJAAAA   storagenetwork{1.8.1} [Storage Network](StorageNetwork-1.8.9-1.8.1.jar) 
    UCHIJAAAA   usefulrecipes{1.1} [UsefulRecipes](UsefulRecipes-1.1.0%281.8.9%29.jar) 
    UCHIJAAAA   usefulstones{0.2} [Useful Stones](UsefulStones_0.2-MCv1.8.9.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)

CorePlugin (Fluxed Redstone-1.3.0.31.jar)

BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    List of loaded APIs: 
        \* AppleCoreAPI (2.0.0) from AppleCore-mc1.8.9-1.3.0.jar
        \* BetterAchievements|API (0.1.1) from BetterAchievements-1.8.9-0.1.1.jar
        \* CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.8.9-1.4.3.20-universal.jar
        \* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        \* CoFHAPI|energy (1.8.9R1.2.0B1) from Foundry-1.8.9-1.4.0.0.jar
        \* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        \* foundry.api (1.4.0.0) from Foundry-1.8.9-1.4.0.0.jar
        \* JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.5.172.jar
        \* McJtyLib (1.8.9-1.8.1beta8) from mcjtylib-1.8.9-1.8.1beta8.jar
        \* pressureAPI (1.3.0.23) from pressure-1.3.0.23-mc1.8.9.jar
        \* reborncoreAPI (1.4.3.20) from RebornCore-1.8.9-1.4.3.20-universal.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        \* WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
    Launched Version: 1.8.9-forge1.8.9-11.15.1.1762
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Invictus-2.1.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
OptiFine Version: OptiFine_1.8.9_HD_U_H4_pre
Render Distance Chunks: 16
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: KUDA-Shaders v6.1.13 BETA - Ultra.zip
OpenGlVersion: 4.5.0 NVIDIA 358.91
OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8
```

**Comment by KidsDontPlay** [comment]
you cannot upgrade storage cables anyway.

**Comment by winsrp** [comment]
See here is where a little GUI change would fix things, make guis with 4 small boxes, were you can put your upgrades (similar as furnus, I think that is yours too), on the ones you can only have 2 upgrades, 2 boxes and on the ones you can't put any... no boxes.

here is an image I made really quick. I took the upgrades background from progressive automation mod.

http://i67.tinypic.com/2hria03.png

**Comment by KidsDontPlay** [comment]
looks ok, I could do that

**Comment by winsrp** [comment]
cool looking forward to it.
