### ISSUE TITLE
Server lag when connecting

### ISSUE THREAD

**Issue by jrpoints** [MrRiegel/Storage-Network#29]
With the latest version 1.8.1 running on a server I can connect and load the world fine for the first time connecting after a restart but if I log out and back in I get timed out and the server hangs for about a minute before letting me log back in. 

Reverting to 1.8.0 fixes the issue.

**Comment by KidsDontPlay** [comment]
could you show me the server log?
and does it occur when you remove all of the cables?

**Comment by jrpoints** [comment]
I have a pretty big system so trying without cables would be annoying, but I did try without the master block and the problem didn't happen

It did lag the server to the point of watchdog shutting it down with this error code, and here are the 2 logs that I know of, If there is more somewhere else let me know and I can get them for you.

error:http://pastebin.com/RqD7iYY8

forge latest log:http://pastebin.com/SfT1h5kU

latest log:http://pastebin.com/tcF6WXRN

**Comment by Brakat07** [comment]
try removing thaumic infusion see if that helps

**Comment by Shadows-of-Fire** [comment]
I was noticing some issues relating to TickProfiler logging the CableMaster Tile as one of the heaviest lag sources in the entire map. That was on 1.12.7 though. It also wasn't so much login lag as it was just the tile lag spiking.

**Comment by Alaberti** [comment]
This should help:
![screenshot from 2016-09-16 164235](https://cloud.githubusercontent.com/assets/10929796/18602462/e3a9bdcc-7c2e-11e6-8f31-9aa47b256668.png)

Edit:
As you build out a bigger network you start noticing lag spikes and "server can't keep up" messages. I use version 1.9.4-1.12.9. Once I'd disconnected my storage controller, the lag immediately stopped. I was running cables through a rather large base, often 150m+ in length.

**Comment by b0bst3r** [comment]
StorageNetwork-1.9.4-1.12.9

1 storage controller is knocking down TPS from 20 to 11-15, it has 136 link cables, 29 storage cables, 11 import, 8 export, 4 tables connected to it.

http://i.imgur.com/gmMpNPx.png

**Comment by KidsDontPlay** [comment]
Yeah, it seems MC cannot handle that bunch of cables. The code isn't written well and I don't know how to make it better. Sorry.
