### ISSUE TITLE
[1.2] NPE on cable GUI - potential fix.

### ISSUE THREAD

**Issue by MrGraphic** [MrRiegel/Storage-Network#3]
Forge .1726
I was trying to open Storage Cable GUI.
[Crash report](https://gist.github.com/MrGraphic/7374eced760d167c87f7)

**Comment by MrGraphic** [comment]
Looks like in order to fix the issue one need to replace all parts of the network - cables at least. That fixed this issue for me.
I will leave this issue open for now for others with similar problem.

**Comment by KidsDontPlay** [comment]
may you try if this works?
https://drive.google.com/file/d/0Bxk8bebSTRk-Vm94bngyU3NDWE0/view?usp=sharing

**Comment by MrGraphic** [comment]
Ok, I rolled back save to try this version for you. Now the part that was crashing is working without issue but if I try to brake cable ( via pick ), cable just brakes - no item form. From logs https://gist.github.com/MrGraphic/74d4fefd6ee282be4cad 
This happens of course only with pre 1.2 cables.
