### ISSUE TITLE
[Request] Arcane Request Table

### ISSUE THREAD

**Issue by codewarrior0** [MrRiegel/Storage-Network#30]
A request table with a wand slot and vis requirement displays, capable of Thaumcraft's Arcane Crafting.

References:

[Thaumcraft 5 API](https://github.com/Azanor/thaumcraft-5-api)
[Thaumcraft 4 API](https://github.com/Azanor/thaumcraft-api)
[Arcane Crafting ME Terminal](https://github.com/Nividica/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/common/parts/PartArcaneCraftingTerminal.java) from ThaumicEnergistics

**Comment by KidsDontPlay** [comment]
maybe sometime. First I want to make the mod stable.

**Comment by Brakat07** [comment]
@MrRiegel  is right if the mod not stable it could destroy your would with thuamcraft
