### ISSUE TITLE
Storage Network version 1.9

### ISSUE THREAD

**Issue by misterfixit** [MrRiegel/Storage-Network#33]
Storage/Export Cables working on separate machine's meaning they aren't connected to the same block or sharing machine's don't function at all. Example I have a set of storage drawers set up in a line horizontally I have storage cables on them, If I have them spaced apart with one block in between them the network recognizes them but if they are touching and there is no space between them the network doesn't recognize them.

**Comment by KidsDontPlay** [comment]
Mmh.. I cannot reproduce. Can you show me a picture of your setup?

**Comment by misterfixit** [comment]
http://puu.sh/og0Ym.jpg -the total storage setup

http://puu.sh/og0Z7.jpg- doesn's show the carrots in the table

**Comment by KidsDontPlay** [comment]
really weird. I built the same setup up and it works fine.
what does the master say when you click it?

**Comment by misterfixit** [comment]
http://puu.sh/ohfhb.jpg

It shows the 4th storage cable but doesn't show the contents, also the export cables share a similar situation they don't export items when next to each other.

**Comment by misterfixit** [comment]
http://puu.sh/ohfxM.jpg

When I attach another cable to the last storage cable it updates on the request table, I'll have to test the export cables.

**Comment by misterfixit** [comment]
The same applies to the export cables. I'm using forge version 1808 by the way.
