### ISSUE TITLE
1019(ish) connected items limit?

### ISSUE THREAD

**Issue by FuzzyBiPolarBear** [MrRiegel/Storage-Network#38]
I've been seeing a bunch of "cannot save chunk" errors ( [File IO Thread/ERROR]: Failed to save chunk java.io.UTFDataFormatException: encoded string too long ) and have whittled it down to having more than 1019 connectables on one system (I have a couple of Advanced Wireless Accessors on there too, so these numbers might affect the totals too, not sure.)

If I add a single extra item (Link Cable or whatever) then the errors are logged about once a minute and the chunk that the Cable Master is in will _not_ be saved.  Removing one item (whatever it is) stops those errors and the chunk starts being saved again.

I can also say that, as a side-note, when approaching this limit the client starts to get rather laggy in the chunks around the system...

**Comment by FuzzyBiPolarBear** [comment]
Closed without comment?

**Comment by KidsDontPlay** [comment]
I didn't wish to fix these bugs. The problems are not important enough.
Just kidding.
Of course I fixed the bugs or at least tried to fix them.

**Comment by FuzzyBiPolarBear** [comment]
Heh, thanks. Was just wondering.
I'll look forward to testing the next release. :)
