### ISSUE TITLE
[Issue] Crash with Storage Drawers

### ISSUE THREAD

**Issue by accessdenied0** [MrRiegel/Storage-Network#42]
Hey @MrRiegel,

I tried to use an _Storage Cable_ on a _Storage Controller_ connected to a set of _Compactors_. The Network seem to show the items only if the "Cable Controller" is near the _Storage Cable_ but it worked. Sadly I got an crash soon I tried to put things back into it: http://pastebin.com/ry1TncvC
Pulling out e.g. Iron worked flawless....

access_denied

**Comment by KidsDontPlay** [comment]
the crash should be fixed
what distance do you mean by 'near'?
or better, could you show your setup?

**Comment by accessdenied0** [comment]
@MrRiegel, 

As I first time set this up, I wasn't able to connect to the controller. Eventually as I set this up like this: http://puu.sh/p7V7w/18a0ca329b.png it worked. I moved the controller now but it seem to work... strange...

It maybe solved itself... thank you anyway and a lot for the fix!

access_denied.
