### ISSUE TITLE
Crash with NPE: Updating screen events

### ISSUE THREAD

**Issue by tommyTT** [MrRiegel/Storage-Network#44]
I crashed twice trying to insert an item (the item storage cable from Storage Network) into my system through the GUI of the item request table. Unfortunately I cannot reproduce this in a test environment. It worked both times after restarting the game and doing the exact same thing. My Storage Network is connected to a controller from Storage Drawers and a few Modular Storage blocks from RFTools. I also used a shift + left click to do it, if that helps. 

http://pastebin.com/GMUJJyGw

**Comment by KidsDontPlay** [comment]
try the latest version and tell me if the crash still occurs

**Comment by tommyTT** [comment]
I played with the newest versions of the mods for an entire day and didn't find any issues, so as far as I'm concerned, this issue is fixed. Thanks. Keep up the good work!

**Comment by RealGrep** [comment]
Unfortunately, I just got this client crash, just now. Logs: http://pastebin.com/3Rtr85di

This is with StorageNetwork-1.9.4-1.11.2.jar, and forge-1.9.4-12.17.0.1957-universal.jar.

**Comment by KidsDontPlay** [comment]
do you play on a server?

**Comment by RealGrep** [comment]
Yep, on my own server running on the same system, for testing and development.

**Comment by KidsDontPlay** [comment]
Should work in the next version
