### ISSUE TITLE
Dupe bug in 1.9.4-1.11.1

### ISSUE THREAD

**Issue by billm** [MrRiegel/Storage-Network#46]
Replicated this with only forge 12.17.0.1950 and Storage Network 1.9.4 - 1.11.1 installed, in both a SSP and SMP game.
1. Place down master node, requester, and storage box (I've been testing with 8, but it might work with one)  See picture.
2. In the requester interface, place item in, then spam double click.

I have a mouse that allows me to macro double click as a single button press, works flawlessly on that, it's a little more tedious without the macro.  I can provide a world save if needed, but it's easy enough to replicate I doubt you will need it.

![2016-06-04_09 57 48](https://cloud.githubusercontent.com/assets/2033/15800311/1a135fa8-2a3b-11e6-8621-0a656831282f.png)

**Comment by KidsDontPlay** [comment]
Hahaha, that's good.
Never again running out of diamonds.
I try to fix it
