### ISSUE TITLE
Storage Network Cable + Crafting Station causes CTD

### ISSUE THREAD

**Issue by slidingmike** [MrRiegel/Storage-Network#47]
[crash-2016-06-09_13.06.02-client.txt](https://github.com/MrRiegel/Storage-Network/files/307503/crash-2016-06-09_13.06.02-client.txt)

**Comment by KidsDontPlay** [comment]
Strange. Actually it cannot happen.

**Comment by slidingmike** [comment]
Sooooo, there's nothing you can do to prevent the crash?

**Comment by KidsDontPlay** [comment]
Yes, I did.

**Comment by slidingmike** [comment]
So it won't crash anymore?

**Comment by KidsDontPlay** [comment]
yep
