### ISSUE TITLE
[Request] Only Read/Write upgrade for Storagebus

### ISSUE THREAD

**Issue by accessdenied0** [MrRiegel/Storage-Network#48]
Hey @MrRiegel,

I guess the title say it all, but I explain it a bit: It is an upgrade for the Storagebus which can adjust to allow him to put in or pull out things. This is different to the export/import -bus because the storagebus doesn't import/export things for itself...

I hope you like that idea.

access_denied

**Comment by KidsDontPlay** [comment]
good idea

**Comment by accessdenied0** [comment]
@MrRiegel,

Thank you^^

I just got one thing I forgot to ask: Is it possible also to add a Filter for OD? Like a "Fuzzy" Filter?

**Comment by KidsDontPlay** [comment]
OD?

**Comment by KidsDontPlay** [comment]
Ok, got it. OreDictionary.
The mod already contains that feature.
Look at the curseforge page.

**Comment by accessdenied0** [comment]
@MrRiegel Sorry,

I totally missed that...

Just one last idea I stole from Refined-Storage (what I think is sadly in to less mods) a thing to filter things with words (names and stuff). 

It might be a bit overdone... because that I mention it here at last. It is a useful thing indeed but I feel like it could be very hard to implement and maybe to much.... 

Anyway I don't know what you think and I'm very thankful for implementing this feature.

[Edit] I found a bug by my instance... (SMP) The OD option doesn't work until I also enable the Metadata option... I think this is not supposed to happen?

**Comment by KidsDontPlay** [comment]
It works for me.
What item do you try to transfer?

**Comment by accessdenied0** [comment]
@MrRiegel,

Just Ores. I have different ones from BaseMaterial (for Poweradvantage), ModernMaterial, FunOres and Substratum (For Foundry). I disabled all but FunOres, only the dimension I mining is generated with all 4 ones.

**Comment by KidsDontPlay** [comment]
ok, I guess I fixed it
