### ISSUE TITLE
[ 1.8.9-1.3 ] Wonky operation upgrade

### ISSUE THREAD

**Issue by MrGraphic** [MrRiegel/Storage-Network#5]
So i was trying **operation upgrade** in newest version and it seems to be "broken". First, it only works in **import cable**. You can of course put this one in export one but it does nothing at least not in test case ( setup with furnace ) Second,  it always grabs more items than specified, like I set 8 i get 12, set 29 I get 32, 3 and get 8 etc. The situation is even wors if I put **stack upgrade** but that seems to be logic.

**Comment by KidsDontPlay** [comment]
You're right. the export cable didn't work. I forgot it ;)
You misinterpreted the operation upgrade. It doesn't stock the amount of items. It makes the cable working if the amount of the specified item in the network is higher (or lower, depends on the redstone torch button) than the specified number.

**Comment by MrGraphic** [comment]
No, no, this is exactly what I was thinking about operation upgrade :).I was expecting that it will turn off cable imediatelly. I probably should consider that there is a delay in transit and during that operation items do not count. Thanks
