### ISSUE TITLE
Inconsistent connection behaviour

### ISSUE THREAD

**Issue by 4rz0** [MrRiegel/Storage-Network#50]
Cables seem to use a system for connecting to inventories that I don't understand.
They sometimes don't connect to valid inventories.
Example:
https://dl.dropboxusercontent.com/s/0342j08z854pxy8/javaw_2016-06-16_12-34-26.png?dl=0
The 2 Storage Cables on the left connect to the 1x Storage Drawer, while the one on the right doesn't.
Is it because it's next to the Farm, because it doesn't know which inventory to connect to?

What about adding some way to force the cable to connect to one of the Inventories in such cases? 

Minecraft version used is 1.9.4, Mod version is 1.11.2

**Comment by KidsDontPlay** [comment]
You're right. the cable cannot decide.
I will look into it
