### ISSUE TITLE
Import cable doesn't work

### ISSUE THREAD

**Issue by Stabington** [MrRiegel/Storage-Network#51]
Hooked up an import cable to a chest, and there's space in my Item Box.
Nothing is happening.

Storage Network 1.11.2
Forge 12.17.0.1965

**Comment by KidsDontPlay** [comment]
Does the cable master have RF?

**Comment by Stabington** [comment]
Oh... it does not. How did I miss that :D

**Comment by KidsDontPlay** [comment]
You could disable the need for RF in the config
