### ISSUE TITLE
[1.9.4] Crash when using wireless acessor to send items

### ISSUE THREAD

**Issue by JCMais** [MrRiegel/Storage-Network#52]
version: 1.11.2

This happens only when you drop the item directly in the grid from the wireless acessor. if you simply shift+click from inventory it works without problem.

log: https://gist.github.com/JCMais/661a5e09c4d3761bf16a85b416a94bce

**Comment by KidsDontPlay** [comment]
did you try the latest version?

**Comment by JCMais** [comment]
I didn't. When the server admin updates the pack I will let you know if the new version fixed it.

**Comment by JCMais** [comment]
The pack was updated, I just tested it and it _works_, that is, it doesn't crash, but doesn't allow to drop the item. You can still shift+click tho. Closing this.
