### ISSUE TITLE
JEI and request table issues

### ISSUE THREAD

**Issue by xannor** [MrRiegel/Storage-Network#53]
Crafting with JEI (using the transfer items) causes items to lose NBT data. My example is if I have a bound blood orb, and I use the plus to craft a rune, the orb that shows up in the table is unbound, however if I do the same at a vanilla crafting bench this does not occur. I can put the orb into the network and pull it out fine, but as soon as I try to craft in the request table it loses its NBT data.

**Comment by KidsDontPlay** [comment]
thanks for the report.
fixed
