### ISSUE TITLE
Items not being seen

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [MrRiegel/Storage-Network#54]
Currently have a few chests hooked to item storage cables then to the master cable, then a separate cable attached to the item request table. The request table can see some items in certain chests, but not all of them. For example, I have acacia logs and coal in one chest (along with other things) and it can see the logs, but not the coal. It also cannot see the ender pearls but can see other items in the chest.

**Comment by awkwaRdcaRRot** [comment]
I should also note that the items were placed in the network using an import cable. When I take the item out and place it into the network via the item request table I can see the items.

**Comment by KidsDontPlay** [comment]
Did you set items into the cable filters?

**Comment by awkwaRdcaRRot** [comment]
That was my first thought as the issue because the one in the example was indeed filtered for acacia after there were already items in there. However after more browsing around I noticed it happened in unfiltered chests as well.

**Comment by KidsDontPlay** [comment]
Could you show me your network? Or better give me your savegame.

**Comment by awkwaRdcaRRot** [comment]
I'll see what I can do this evening when I get home from work. I have sort of dixed

**Comment by awkwaRdcaRRot** [comment]
I can see what I can do tonight when I get home from work. I have gotten everything to show up in the network by just grabbing everything and throwing it in the network through the item request table. I'll see if I can recreate the issue in another world and send that over. (Sorry about the close and reopen, I hit the wrong button on mobile)

**Comment by awkwaRdcaRRot** [comment]
Ya know, I couldn't recreate the issue. I have a theory. I filtered the cable and accidentally used quark's drop off from inventory button without using the "smart" feature and it dropped it off in a chest that it wasn't supposed to (which I can recreate). Is there any way to make it so items in the wrong filtered chest are still visible in the network?

**Comment by KidsDontPlay** [comment]
Currently no

**Comment by awkwaRdcaRRot** [comment]
Ah ok, no worries. Thanks for the time and effort you put into this mod!
