### ISSUE TITLE
Have some way to show fluid in network

### ISSUE THREAD

**Issue by 4rz0** [MrRiegel/Storage-Network#58]
Let's have some way to view the amount of fluid inside a network.
Not even the Fluid Boxes themselves display their content when placed down, nor do any of the other access ways.

**Comment by KidsDontPlay** [comment]
Fluid Request Table?

**Comment by 4rz0** [comment]
Oh, I never saw this one.
Oh well.

Can be closed :D

**Comment by KidsDontPlay** [comment]
and Fluid Wireless Accessor will work too
