### ISSUE TITLE
1.8.9-Tinker's Smeltery only shows one liquid

### ISSUE THREAD

**Issue by WenXin20** [MrRiegel/Storage-Network#60]
When a tinkers construct smeltery is connected, the fluid request table only shows the selected liquid. 

For example, if you click on the molten iron in the smeltery controller, the request table only shows molten iron, then if you select molten gold, it will only show gold and the iron doesn't appear in the request table.

**Comment by KidsDontPlay** [comment]
I no longer support 1.8. Sorry.
