### ISSUE TITLE
[Client Crash] placing a cable master on top of an item access table

### ISSUE THREAD

**Issue by APolarBaer** [MrRiegel/Storage-Network#63]
http://pastebin.com/7iwaydbT

**Comment by KidsDontPlay** [comment]
Use the latest version

**Comment by APolarBaer** [comment]
does the newest version fix https://github.com/MrRiegel/Storage-Network/issues/45 aswell?

**Comment by KidsDontPlay** [comment]
unfortunately no

**Comment by APolarBaer** [comment]
good luck with that D: , the mod is cool but i cant see myself using it too much untill thats fixed, i lost probably around half the stuff i put into mine
