### ISSUE TITLE
duplicate id when playing on server(1.9.4)

### ISSUE THREAD

**Issue by SDUBZ** [MrRiegel/Storage-Network#64]
i was playing today on my server and it hard crashed after awhile back to desktop 

crashlog: 
[crash-2016-07-06_23.53.40-client.txt](https://github.com/MrRiegel/Storage-Network/files/356424/crash-2016-07-06_23.53.40-client.txt)
forge 1.9.4-1976

**Comment by KidsDontPlay** [comment]
Use the latest version pls
