### ISSUE TITLE
I can no longer use the item wireless accessor

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [MrRiegel/Storage-Network#67]
The title. I opened up my world after updating and can no longer use the item wireless accessor. Everything else seemingly still works, can't speak on the fluid wireless accessor, as I am not using it currently.

**Comment by KidsDontPlay** [comment]
did you try clicking the master with accessor again?
does it work in another world?

**Comment by awkwaRdcaRRot** [comment]
It does work in a different world (singleplayer). I am using this on a server by the way. I did try and click the master again, and I tried breaking the master, replacing, and clicking it again.
