### ISSUE TITLE
fluid export cable doesn't  work with fluid tank from enderio any more 

### ISSUE THREAD

**Issue by Brakat07** [MrRiegel/Storage-Network#68]

**Comment by Brakat07** [comment]
i update to least and didn't work

**Comment by KidsDontPlay** [comment]
did it work 1.12.4?

**Comment by canitzp** [comment]
This is because I disable the old fluid system with my pull request to preved it to crash with many tanks. EnderIO is using old and deprecated stuff, pe example the old fluid system. It's not the fault of this mod.

**Comment by Brakat07** [comment]
@MrRiegel no

**Comment by Brakat07** [comment]
@canitzp oh but that destroy my build 
4 tank from ender io with lava 
64 diamond generator from Progressive Automation
64 lava buckets 
automatic  
10240RF

**Comment by canitzp** [comment]
change the tanks from enderio

**Comment by Brakat07** [comment]
_10240RF/tick_

**Comment by Brakat07** [comment]
with what

**Comment by canitzp** [comment]
I don't no wich modpack you're playing. Maybe with some from neotech

**Comment by Brakat07** [comment]
no modpack just random mods i put togather

**Comment by Brakat07** [comment]
dose neotech fell the bucket automatically?

**Comment by canitzp** [comment]
I don't know

**Comment by Brakat07** [comment]
i hate how 1.9 and up mods behave and the code

**Comment by canitzp** [comment]
SleepyTrousers/EnderIO#3375

**Comment by Brakat07** [comment]
yeah the fluid handler is so bad for forge 1.9 and up

**Comment by Brakat07** [comment]
i have a Q can i use 1.10.2 enderio in 1.9.4

**Comment by KidsDontPlay** [comment]
doesn't EIO already use capabilities?
https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/tank/TileTank.java#L333

EDIT: oh, thats only for 1.10

**Comment by KidsDontPlay** [comment]
I don't think that 1.10 EIO runs on 1.9. You could try

**Comment by canitzp** [comment]
Forge for 1.9.4 and 1.10/1.10.2 are nearly fully compatible. just try it , but try to update all your mods to 1.10.2

**Comment by Brakat07** [comment]
no it doesn't but i will try hope for the best 
for some reason it work just fine on 1.12.3 i dont now why

**Comment by Brakat07** [comment]
ok i will try ender io 1.10.2

**Comment by Brakat07** [comment]
it doesn't work ender io 1.10.2 and endercore

**Comment by canitzp** [comment]
It work's with 1.12.3 because I deleted the old system in 1.12.4

**Comment by Brakat07** [comment]
yeah i now it works on 1.12.3

**Comment by Brakat07** [comment]
what

**Comment by Brakat07** [comment]
i understand now what do you mean now
