### ISSUE TITLE
[Request] Add speed modifiers to importers and exporters.

### ISSUE THREAD

**Issue by choekstr** [MrRiegel/Storage-Network#73]
I had an RFTools modular storage with almost 300 stacks of items (not all were full stacks).  I ran a cable with importer on it and pulled in the inventory but went and had dinner and came back an hour later and it had finally finished.  It is painfully slow to pull in large amounts of items.

Ideally we would have both speed upgrades and stack upgrades to allow for a stack at a time.  This is something we have seen in AE1/2 and RefinedStorage as it is a really nice thing to have.

Hopefully this is something fairly trivial to implement?

**Comment by KidsDontPlay** [comment]
What do you think do the speed upgrade and the stack upgrade do?

**Comment by choekstr** [comment]
Their function would be to take an inventory of say 300 stacks of items and import them into the network at a faster rate.  Either by more items per tick (speed upgrade) or by a stack at a time (stack upgrade).  If I have a diamond chest full of items that I want to automatically import it seems to take a really long time for that 1 chest.

**Comment by KidsDontPlay** [comment]
Actually it was a rhetorical question. There are already those upgrades in the mod since months.

**Comment by choekstr** [comment]
Ok, so digging in a bit deeper, if you search JEI for "@storage network" it only shows part of the mod and doesn't include the covers and staff, nor the upgrades.  If you search for @storagenetwork then it shows the full mod.  
Ok, nevermind.  Just me derping and putting a space in the search string.
