### ISSUE TITLE
Block Liquidator working properly but rendering incorrectly

### ISSUE THREAD

**Issue by utoc** [MrRiegel/Storage-Network#74]
Using:

```
forge-1.10.2-12.18.1.2045
StorageNetwork-1.9.4-1.12.7
MC 1.10.2
```

The block liquidator is properly breaking the block on the opposite side as the one that it was placed on, however, the breaking face ALWAYS renders facing south

Seen here: http://i.imgur.com/P2LrcLJ.gifv

**Comment by KidsDontPlay** [comment]
I cannot reproduce the problem.
Does it happen often?
Does the log say something unusual?

**Comment by utoc** [comment]
Ok, I have a little more information that may help.  The block doesn't want to render the breaking face on the top side and bottom side.  It will render N, E, S and W.  Sorry, that took a while to narrow down.  There are no complaints on the server console or in the client/server log

See attached: http://i.imgur.com/OQoi8T5.gifv

When placing it on the blocks above, instead of the breaking face being on the bottom, it reverts to the south side.  When placing it on the ground, instead of the breaking face being on the top, it reverts to the south.  when placed in a hole aiming at the block behind, south of it, the breaking face is rendered on the north side which is correct.

**Comment by KidsDontPlay** [comment]
Sorry, I cannot reproduce it anyway. Even on a server it works fine for me

**Comment by utoc** [comment]
Give me a couple of days to try to single out the interaction that is causing this.  It appears to be specific to server/client only and my setup differs from yours; I will update then.

**Comment by utoc** [comment]
I'm going to close this ticket for now.  It is an interaction with another mod and can only be replicated on a server/client environment which makes it pretty niche.  If I ever find time to track it down I will re-report it then.
