### ISSUE TITLE
[MC 1.8.9] Cable Master doesn't consume energy

### ISSUE THREAD

**Issue by Naheulf** [MrRiegel/Storage-Network#76]
Hello,
The cable master doesn't consume energy even if "energyNeeded=true" is set in the config file.
Minecraft version : 1.8.9
Forge version : 11.15.1.1902
Storage Network version : 1.8.9-1.11.1-final

Here is my config file :
[storagenetwork.cfg.txt](https://github.com/MrRiegel/Storage-Network/files/416715/storagenetwork.cfg.txt)

**Comment by KidsDontPlay** [comment]
I don't support 1.8.9 anymore. Please use 1.9/1.10
