### ISSUE TITLE
Request table enhancements

### ISSUE THREAD

**Issue by MrGraphic** [MrRiegel/Storage-Network#8]
So, I've been using StorageNetwork for quiet a while now and there are few things that could work better ( in my opinion of course ).
- [x] Item retrieving; for now it just put items in inventory, stack or one item. It would be fantastic to have at least vanilla style of item grabbing
  
  LMB - grab stack
  Shift LMB - put stack in inv.
  RMB - grab half a stack
  Shift RMB  grab 1/4 of stack or 1/8 for example
  Ctrl RMB grab one item
  
  ...or similar to this. It would be much easier to operate on stacks.
- [x] ~~lock on actually highlited item so it will not change its position while retrieving in "amount" sorting mode~~ - lost its importance as of 1.5
- [x] <del>more sorting modes - byt modID, by oreDict, by type.</del>
- [x] <del>RMB on search field to clear text - no need to say how usefull is this :)</del>
- [x] ~~ghost items in crafting grid instead of actual items - while it is not that important ppl proved that it is usefull~~ - rejected for now
- [x] <del>support for [CrafttingTweaks](http://minecraft.curseforge.com/projects/crafting-tweaks)</del>

These are pretty common ideas and it would be fantastic to have them on board :).

**Comment by MrGraphic** [comment]
Formated sugestion list a little and crossed out implemented things. Thanks @MrRiegel, it is now much more convenient especially clear on right click, you have no idea ;).

**Comment by KidsDontPlay** [comment]
ok, thanks.
I don't much like the idea of ghost items. maybe sometime
For locking an item you could just type the name in the search bar

**Comment by MrGraphic** [comment]
Ah, good to hear from you. Locking thing lost its importance now as we have all these additional things like search modes and clearing :). Editing...

**Comment by MrGraphic** [comment]
Oh, and there is one more thing that would be raelly nice to have ( don't want to open separate issue for this one only ):
- Supplier/Regulator upgrade for export cables

Of course we have operation upgrade that will turn off cable based on number of items in network but having ability to keep only specific amount of items in the target container would be very usefull.
And I'm not talking about one item but combination of different items. 
I found BC auto workbench to be very usefull with current SN. I can set recipe, hook export cable to the back, storage cable to the front and voila, **auto crafting setup**. With proposed upgrade it would work much better :).

**Comment by KidsDontPlay** [comment]
Ok, are you pleased with this?

SHIFT- into inventory
NO SHIFT - grab

LMB - 64
RMB + NO CTRL - 32
RMB + CTRL - 1

**Comment by MrGraphic** [comment]
Hehe, looks good to me :).
