### ISSUE TITLE
1.10.2 (1.12.9) Some modded items cannot be retreived from request table once put in

### ISSUE THREAD

**Issue by LordHellscream** [MrRiegel/Storage-Network#82]
Some modded items cannot be retrieved from the request table after a while (may be able to take it out right away, but after a while it cannot be taken out). you can still of course track down the item from the actual chest/containers but its a pain.

So far I've noticed:
1. Soul vials from ender io.
2. cardboard boxes from Mekanism

I am using the basic storage crate from Actually Addition as item containers.

**Comment by KidsDontPlay** [comment]
the bug is already known but I don't know how to fix it

**Comment by DoomSquirter** [comment]
happens with silent gems swords as well.  Starting to see a trend with nbt data probably?
