### ISSUE TITLE
Bug Report: Storage Network

### ISSUE THREAD

**Issue by Traverse-Joe** [MrRiegel/Storage-Network#83]
So if you use a lot of item boxes and start filling them rapidly they eventually delete existing inventory to make more room rather than no longer accept items

**Comment by KidsDontPlay** [comment]
I don't understand what you mean.

**Comment by Traverse-Joe** [comment]
so on my stream on mmd my viewers and the RealP455w0rd witnessed it when I was looking in my item request and could see the items disappearing I woke up and checked my system and almost everything was missing and no one is trolling

**Comment by KidsDontPlay** [comment]
So your items vanish. Can you reproduce this and can you tell me the steps so I can reproduce it?
