### ISSUE TITLE
attaching export/import cable to a machine when there are multiple adjacents

### ISSUE THREAD

**Issue by DoomSquirter** [MrRiegel/Storage-Network#85]
Is there a method to attach a export/import cable to a machine when there is another machine near same block?  It always seems like it's rng that chooses which one it'll connect to.

I have to break all but the machine I want connecting to (or chest/container) then attach cable, then put back the other machines/containers.

Possibly a way to rotate the cable somehow?

**Comment by KidsDontPlay** [comment]
Currently no
