### ISSUE TITLE
Edge Case - Items stuck in storage network

### ISSUE THREAD

**Issue by utoc** [MrRiegel/Storage-Network#86]
Greetings,

I have an edge case to present with StorageNetwork.  Some items that hold meta/nbt data such as BloodMagic's Common tartaric gem and EnderIOs soul vial under unknown circumstances are stuck and cannot be removed.  We've tried export busses to no avail.

We ran across this issue in Refined Storage and while it may not be a similar issue, it might give you somewhere to start.

Picture that isn't entirely helpful: http://i.imgur.com/9FFy9F2.png

Those vials can't be removed.

I cannot reproduce this on command but I do have a user that has two soul vials permanently stuck.

No errors on the server or client when trying to remove said stuck items.

Running SN 1.9.4-1.12.9 with FML 2094

**Comment by canitzp** [comment]
#82
