### ISSUE TITLE
Items in double chests from Quark being counted twice.

### ISSUE THREAD

**Issue by thecanidcoder** [MrRiegel/Storage-Network#89]
EDIT: Reported to Quark repo at Vazkii/Quark#209

Items put into one side of double chests from [Quark](https://minecraft.curseforge.com/projects/quark) are being counted twice by Storage Network. Vanilla double chests and chests from Iron Chests behave as expected.

To clarify, putting an item into one side of the double chest gives me the normal result (aka, 1 item is counted as 1 item), but putting them into the other side gives a doubled count. The items are not actually duplicated when extracting them, they are simply counted twice.

![2016-11-02_14 31 36](https://cloud.githubusercontent.com/assets/22875626/19942385/eaddda7e-a109-11e6-8997-99998298a185.png)
![2016-11-02_14 32 36](https://cloud.githubusercontent.com/assets/22875626/19942404/fc2e35ee-a109-11e6-90bb-30ab768113a7.png)
![2016-11-02_14 32 39](https://cloud.githubusercontent.com/assets/22875626/19942407/ff15fbb6-a109-11e6-9d6a-bf87a732b03b.png)
![2016-11-02_14 32 46](https://cloud.githubusercontent.com/assets/22875626/19942410/00ad6b26-a10a-11e6-942f-8c8bbc6eaf1a.png)

**Comment by KidsDontPlay** [comment]
did you connect 2 storage cables to the double chest? (one per block)

**Comment by thecanidcoder** [comment]
No, it's only one cable.
![2016-11-02_15 17 46](https://cloud.githubusercontent.com/assets/22875626/19943838/8d564138-a10f-11e6-98b6-06ebbf7b46ed.png)

**Comment by KidsDontPlay** [comment]
and single quark chests work well?

**Comment by thecanidcoder** [comment]
Just tested, and they seem to be working normally in every instance I can think to test.

**Comment by thecanidcoder** [comment]
Just a note, Quark dev appears to be acknowledging this as a Quark issue; my bug report has been closed as a dupe of Vazkii/Quark#176.

**Comment by KidsDontPlay** [comment]
ok
