### ISSUE TITLE
[Request] Compatibility with InventoryTweaks.

### ISSUE THREAD

**Issue by thecanidcoder** [MrRiegel/Storage-Network#92]
Would like to be able to use the "Deposit All" and "Deposit All of Same Type" shortcuts from the InventoryTweaks mod.

**Comment by KidsDontPlay** [comment]
I have never heard about that feature. Do you mean this [mod](https://minecraft.curseforge.com/projects/inventory-tweaks)?

**Comment by thecanidcoder** [comment]
Yessir. 

For example, with that mod, you can hit Ctrl+Shift+Left Click on one stack of Cobble and it will move all stacks of Cobble from your inventory into a chest, or vice versa. Ctrl+Space+Left Click will simply move all items in either container into the other one.

It's a very commonly-used mod and works with almost every inventory, including other mods similar to this one like AE2.

**Comment by KidsDontPlay** [comment]
I guess it's not possible to add support for inventory tweaks but I can implement said features on my own.

**Comment by thecanidcoder** [comment]
No? Again, AE2 supports Inventory Tweaks 100% for moving things into the system. Moving them out again obviously doesn't work because that would get crazy.

If implementing them yourself, please try to detect Inventory Tweaks and act accordingly, to avoid conflicts.

Thanks for your attention!
