### ISSUE TITLE
Quantumn storage integration

### ISSUE THREAD

**Issue by GodsVictory** [MrRiegel/Storage-Network#93]
You are currently able to attach a storage cable to quantum storage units, but it only shows what is currently in the "out" slot instead of the total amount.

**Comment by KidsDontPlay** [comment]
that should be fixed by quantum storage

**Comment by GodsVictory** [comment]
I just assumed since it reports correctly in refined storage

**Comment by GodsVictory** [comment]
It looks like quantum storage has an open issue concerning this

https://github.com/gigabit101/QuantumStorage/issues/44
