### ISSUE TITLE
We are almost there. 

### ISSUE THREAD

**Issue by demethan** [MrRiegel/Storage-Network#96]
2.0.5,  for a server setup.  In continuation to Topher's issue. 
this is on the same server with the BreakFastSpecial pack. 

We are testing and here is what I obsverve. 

-Slow show of item.
-searching for items will kick you from the interface. then the interface is inaccessible after a few seconds. The one probe says "Controller not responding"
-Switching the JEI button while in the terminal will not work. if you get out of the terminal and in again. the JEI change will work. 

Ill keep you posted if I find other thing..  

I Do love the rewrite... Keep it up... we love your mod. 

*edit 
if this can help. here is the fml-server-latest.log  http://paste.ubuntu.com/23496178/

**Comment by demethan** [comment]
Precision on the search:  once you get kicked from the terminal, if you go back in and search the same thing, you do get the results.

Also here is a few pic of the setup. 

![2016-11-18_12 00 19](https://cloud.githubusercontent.com/assets/5810363/20438767/c3b43248-ad86-11e6-8dba-71a9da650761.png)
![2016-11-18_12 00 25](https://cloud.githubusercontent.com/assets/5810363/20438768/c3b53b52-ad86-11e6-80c2-af5892fe00d4.png)
![2016-11-18_12 00 38](https://cloud.githubusercontent.com/assets/5810363/20438766/c3b42992-ad86-11e6-9f15-b2d276492562.png)

**Comment by KidsDontPlay** [comment]
try with latest limelib version

**Comment by demethan** [comment]
Seems all good. thx.
