### ISSUE TITLE
Stocking upgrade.

### ISSUE THREAD

**Issue by demethan** [MrRiegel/Storage-Network#97]
Hi, 

Is the stocking upgrade going to come back in 2.x?

thanks

**Comment by KidsDontPlay** [comment]
yes.
but I currently don't know how it should work, because I changed the UI in 2.x.
Do you have an idea? Shall the upgrades itself have an UI where you can specify the item and amount?

**Comment by demethan** [comment]
Even if you make a separate bus, and recolonize the import bus blue or green. That would be fine.
